### ISSUE TITLE
Upload speed is capped at 700K 

### ISSUE THREAD

**Issue by Konstantinusz** [jbd/httpfs2#1]
When I mount a direct URL, and then I try to upload the file to a server with cURL, the upload speed is capped at around 400K (httpfs2) and 700K (httpfs2-mt). When I try to copy the file with "cat" and redirection, and measuring the speed with "pv" utility, speed is capped at 1.4 MB / sec. However the download speed from the direct URL and the upload speed to the server isn't limited that much, I tried with a similar utility called "avfs" or "avfsd". Using same direct URL upload speed and copying also was about 10 MB / sec. However avfsd always choke at 100 MB transferred, and speed decreases to 100 K/sec. Is there any internal buffer size or option which should be altered to remove this annoying speed limitation? (I am using Arch Linux, 4.5.1-1-ARCH)

**Comment by jbd** [comment]
This is not an official repository, sorry.
